name: CI ORG Validation
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install Salesforce CLI
      run: |
        npm install sfdx-cli
        node_modules/sfdx-cli/bin/run --version
        node_modules/sfdx-cli/bin/run plugins --core
      
    - name: Authenticate CI ORG
      run: |
        echo "${SALESFORCE_JWT_SECRET_KEY}" > server.key
        node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid ${{ secrets.CI_CONSUMER_KEY }} --jwtkeyfile server.key --username ${{ secrets.CI_USERNAME}} --instanceurl ${{ secrets.SFDC_SANDBOX_HOST}} 
      env:
        SALESFORCE_JWT_SECRET_KEY: ${{ secrets.SALESFORCE_JWT_SECRET_KEY }}

    - name: Validate CI ORG
      run: node_modules/sfdx-cli/bin/run force:source:deploy -p force-app/main/default -u chand@ci.com -c
